doc.type.html
html lang en 
script
header=document create.element(header)
header.style.backgroundcolor=#4caf50
header.style.color=’white’
header.style.padding=’10px’
header.style.textalign=’center’
header.style.text.fontsize=’24px’
header.textcontent=’welcome to covid strings8’
document appendchild(header)
<header.html>
heading variables 
the heading numbers that determine where each heading and subheading go 
heading1=keywords
heading2=online references 
heading3=script templates
filename=covid strings 8 key words.js
<header.html>
keywords
key search words for covid strings8
covid strings 8 key word list=[trackers use personal data,using covid tracker,knowledge is power,relaxation strategies covid prescription,uv light,health impacts change,bleach use hard surfaces,covid fatigue real]
string manager non-concatenated
insert string(entity,string)
entity.element.text=string
string manager insert string
string=””
string manager concatenated
insert string(entity,string)
entity.element.text=string
string manager insert string
string=””
for string in covid strings key word list
select characters
edit diffuse property
desired color=green
<header.html>
online references 
links to articles that correspond to phrases in covid strings8
covid strings8 reference list=[a:malicious covid-19 tracker apps are stealing peoples data (mobilesyrup.com),b:covid risk and tracking tools:how to use them safely -the washington post,c:anthony fauci to testify for house committee investigating origins of covid (msn.com),d:why you should rest if you have covid-19 |time,e:covid-19 drugs:are there any that work?,-mayo clinic,f:comparing covid-19 pills:paxlovid vs.molnupiravir(lagevrio)-goodrx,g:2023 lexus rx 350 review,pricing, & pictures |us news (usnews.com),
h:does uv light kill coronavirus?facts and myths (healthline.com),i:people who followed covid recommendations more likely to have mental health issues now (msn.com),j:people want to use bleach and antiseptic for covid and are calling us for advice(theconversation.com),k:covid-19  disinfecting with bleach -center for research on ingredient safety (msu.edu),l:covid apathy and fatigue are real.heres how to cope|cnn, m:covid-19 fatigue: what to know (webmd.com),
n:does colloidal silver work for covid-19? -the atlantic,o:expert warns europe to prepare for worst-case scenario over china outbreak (msn.com),p:doctor describes chinas overwhelmed hospitals verge of collapse(msn.com),q:ivermectin |covid-19 treatment guidelines (nih.gov),r:dietary supplements in the time of covid-19 -health professional fact sheet (nih.gov),s:juice wrld  lucid dreams lyrics |genius lyrics,t:brutal new poll shows trump losing big to biden,even with third party spoiler (msn.com),u:how two high school students solved a 2,000-year-old  math puzzle (msn.com)]
<header.html>
script templates
code for accessing the references
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
a=pc.create script(a);
a.attributes.add(foobar,{type:entity});
a.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
b=pc.create script(b);
b.attributes.add(foobar,{type:entity});
b.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
c=pc.create script(c);
c.attributes.add(foobar,{type:entity});
c.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
d=pc.create script(d);
d.attributes.add(foobar,{type:entity});
d.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
e=pc.create script(e);
e.attributes.add(foobar,{type:entity});
e.prototype.initialize=function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
f=pc.create script(f);
f.attributes.add(foobar,{type:entity});
f.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
g=pc.create script(g);
g.attributes.add(foobar,{type:entity});
g.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
h=pc.create script(h);
h.attributes.add(foobar,{type:entity});
h.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
i=pc.create script(i);
i.attributes.Add(foobar,{type:entity});
i.prototype.initialize =function() 
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
j=pc.create script(j);
j.attributes.add(foobar,{type:entity});
j.prototype.initialize=function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
k=pc.create script(k);
k.attributes.add(foobar,{type:entity});
k.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
l=pc.create script(l);
l.attributes.add(foobar,{type:entity});
l.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
m=pc.create script(m);
m.attributes.add(foobar,{type:entity});
m.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
n=pc.create script(n);
n.attributes.add(foobar,{type:entity});
n.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
o=pc.create script(o);
o.attributes.add(foobar,{type:entity});
o.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
p=pc.create script(p);
p.attributes.add(foobar,{type:entity});
p.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
q=pc.create script(q);
q.attributes.add(foobar,{type:entity});
q.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
r=pc.create script(r);
r.attributes.add(foobar,{type:entity});
r.prototype.initialize =function()
console.log(this.foobar.name);
asset=this app.assets.find()
template asset resource 
entity template instantiate
entity script foobar=this entity
entity reparnet (this.entity)
s=pc.create script(s);
s.attributes.add(foobar,{type:entity});
s.prototype.initialize =function() 
console.log(this.foobar.name);
return filename
